name: Get tag

on:
  push:
    tags:
      - '*'

description: Get tag from GITHUB_REF environment variable
branding:
  icon: tag
  color: purple
outputs:
  tag:
    description: The name of the git tag extracted from GITHUB_REF.

runs:
  using: node18
  main: main.js